Add Yekan(B-Yekan) font
mahdyar/persian-fonts-flutter pull request #4
Opened 2021-12-08 12:38 UTC by SajadRahimi1

add another Persian font that name is Yekan.

2021-12-09 17:21 UTC, mahdyar requested changes
Hello @SajadRahimi1 and thank you for your contribution;
please review the suggestion(s) and then ask for another review. :)

2021-12-09 17:21 UTC, mahdyar commented on example/lib/main.dart
> +        ));
Please don't change indention and leave it as it is, it probably happened because you use some code formatter.

2021-12-11 05:30 UTC, SajadRahimi1 reviewed
change example/lib/main.dart like main code

2021-12-11 15:11 UTC, mahdyar approved these changes
Thank you, @SajadRahimi1!

2021-12-11 15:11 UTC, merged